import type { INodeProperties } from 'n8n-workflow';

export const baseProperties: INodeProperties[] = [
  {
    displayName: 'Access Token',
    name: 'accessToken',
    type: 'string',
    typeOptions: { password: true },
    default: '',
    required: true,
    description: 'Bearer token emitido pelo endpoint de autorização. Geralmente vem por expressão de um node anterior.',
  },
  {
    displayName: 'Operation',
    name: 'operation',
    type: 'options',
    noDataExpression: true,
    default: 'listCategories',
    options: [
      {
        name: 'Buscar Produtos',
        value: 'searchProducts',
        description: 'POST /products/search',
        action: 'Buscar produtos por filtro',
      },
      {
        name: 'Listar Categorias',
        value: 'listCategories',
        description: 'GET /category',
        action: 'Listar categorias de produto',
      },
    ],
  },
];

export const listCategoriesProperties: INodeProperties[] = [
  {
    displayName: 'Retornar Todos',
    name: 'returnAll',
    type: 'boolean',
    default: false,
    displayOptions: { show: { operation: ['listCategories'] } },
    description: 'Whether to return all results or only up to a given limit',
  },
  {
    displayName: 'Limite',
    name: 'limit',
    type: 'number',
    typeOptions: { minValue: 1 },
    default: 50,
    displayOptions: { show: { operation: ['listCategories'], returnAll: [false] } },
    description: 'Max number of results to return',
  },
  {
    displayName: 'Filtros',
    name: 'filters',
    type: 'collection',
    placeholder: 'Adicionar filtro',
    default: {},
    displayOptions: { show: { operation: ['listCategories'] } },
    options: [
      {
        displayName: 'Data De Alteração (Fim)',
        name: 'EndChangeDate',
        type: 'dateTime',
        default: '',
        description: 'EndChangeDate — filtra registros alterados até esta data',
      },
      {
        displayName: 'Data De Alteração (Início)',
        name: 'StartChangeDate',
        type: 'dateTime',
        default: '',
        description: 'StartChangeDate — filtra registros alterados a partir desta data',
      },
      {
        displayName: 'Ordenação',
        name: 'Order',
        type: 'string',
        default: '',
        placeholder: 'code asc',
        description: 'Order — campo e sentido da ordenação',
      },
    ],
  },
  {
    displayName: 'Campos a Retornar',
    name: 'fields',
    type: 'multiOptions',
    default: [],
    displayOptions: { show: { operation: ['listCategories'] } },
    description: 'Se vazio, retorna todos os campos. Caso contrário, apenas os selecionados são incluídos na saída.',
    options: [
      { name: 'changeDate', value: 'changeDate' },
      { name: 'code', value: 'code' },
      { name: 'description', value: 'description' },
      { name: 'insertDate', value: 'insertDate' },
      { name: 'level', value: 'level' },
      { name: 'parentCode', value: 'parentCode' },
    ],
  },
];

export const searchProductsProperties: INodeProperties[] = [
  {
    displayName: 'Retornar Todos',
    name: 'returnAll',
    type: 'boolean',
    default: false,
    displayOptions: { show: { operation: ['searchProducts'] } },
    description: 'Whether to return all results or only up to a given limit',
  },
  {
    displayName: 'Limite',
    name: 'limit',
    type: 'number',
    typeOptions: { minValue: 1 },
    default: 50,
    displayOptions: { show: { operation: ['searchProducts'], returnAll: [false] } },
    description: 'Max number of results to return',
  },
  {
    displayName: 'Filtros',
    name: 'filter',
    type: 'collection',
    placeholder: 'Adicionar filtro',
    default: {},
    displayOptions: { show: { operation: ['searchProducts'] } },
    options: [
      {
        displayName: 'Apenas Ativos',
        name: 'isActive',
        type: 'boolean',
        default: true,
        description: 'Whether to return only active products',
      },
      {
        displayName: 'Change Date (Fim)',
        name: 'endChangeDate',
        type: 'dateTime',
        default: '',
        description: 'Filtrar produtos alterados até esta data',
      },
      {
        displayName: 'Change Date (Início)',
        name: 'startChangeDate',
        type: 'dateTime',
        default: '',
        description: 'Filtrar produtos alterados a partir desta data',
      },
      {
        displayName: 'Lista De Códigos De Produto',
        name: 'productCodeList',
        type: 'string',
        default: '',
        placeholder: '12345,67890',
        description: 'Lista de códigos separados por vírgula',
      },
      {
        displayName: 'Lista De Códigos De Referência',
        name: 'referenceCodeList',
        type: 'string',
        default: '',
        placeholder: 'REF001,REF002',
        description: 'Lista de referências separadas por vírgula',
      },
    ],
  },
  {
    displayName: 'Expand',
    name: 'expand',
    type: 'multiOptions',
    default: [],
    displayOptions: { show: { operation: ['searchProducts'] } },
    description: 'Dados adicionais a expandir na resposta',
    options: [
      { name: 'additionalVariations', value: 'additionalVariations' },
      { name: 'classifications', value: 'classifications' },
      { name: 'stocks', value: 'stocks' },
      { name: 'suppliers', value: 'suppliers' },
    ],
  },
  {
    displayName: 'Campos a Retornar',
    name: 'fields',
    type: 'multiOptions',
    default: [],
    displayOptions: { show: { operation: ['searchProducts'] } },
    description: 'Se vazio, retorna todos os campos. Caso contrário, apenas os selecionados são incluídos na saída.',
    options: [
      { name: 'categoryCode', value: 'categoryCode' },
      { name: 'changeDate', value: 'changeDate' },
      { name: 'insertDate', value: 'insertDate' },
      { name: 'isActive', value: 'isActive' },
      { name: 'productCode', value: 'productCode' },
      { name: 'productName', value: 'productName' },
      { name: 'referenceCode', value: 'referenceCode' },
    ],
  },
];

export const totvsModaProdutoProperties: INodeProperties[] = [
  ...baseProperties,
  ...listCategoriesProperties,
  ...searchProductsProperties,
];
